import { sleep } from '../harness.mjs';
import { startMatchUI } from '../lib.mjs';
export default async function (c) {
  const page = await c.open('http://127.0.0.1:4173/?quality=low&scale=0.5');
  await startMatchUI(page, { team: 'CT', seed: 61 }); await c.ensureLocked();
  await c.ev(() => window.__cs2.freezeBots(true)); await c.ev(() => window.__cs2.setPhaseTime(0.3)); await c.waitPhase('live'); await c.ev(() => window.__cs2.setPhaseTime(600));
  await c.ev(() => window.__cs2.giveWeapon('awp')); await sleep(1500);
  const enemy = (await c.ev(() => window.__cs2.actors())).find(a => a.team === 'T');
  await c.ev(id => window.__cs2.teleport(38, 0, 180, id), enemy.id); await c.ev(() => window.__cs2.teleport(38, 30, 0)); await sleep(300); c.mx = 640; c.my = 360; await c.aimAtPoint(38, 1.2, 0); await sleep(300);
  const f0 = await c.ev(() => window.__cs2.fov()); await c.shot('awp_unscoped');
  await c.click(60, 'right'); await sleep(400); const f1 = await c.ev(() => window.__cs2.fov()); const s1 = (await c.state()).player; await c.shot('awp_zoom1');
  c.step('first RMB: zoom level 1, FOV 40, overlay on, viewmodel hidden', s1.zoom === 1 && f1.target === 40 && f1.scopeOverlay && !f1.viewmodelVisible, f1);
  await c.click(60, 'right'); await sleep(400); const f2 = await c.ev(() => window.__cs2.fov()); const s2 = (await c.state()).player; await c.shot('awp_zoom2');
  c.step('second RMB: zoom level 2, FOV 10', s2.zoom === 2 && f2.target === 10, f2);
  await c.click(60, 'right'); await sleep(400); const s3 = (await c.state()).player; c.step('third RMB: back to unscoped, FOV restored', s3.zoom === 0 && (await c.ev(() => window.__cs2.fov())).target === f0.target);
  const y0 = (await c.state()).player.yaw; await page.mouse.move(c.mx + 300, c.my); c.mx += 300; await sleep(150); const y1 = (await c.state()).player.yaw;
  await c.click(60, 'right'); await sleep(300); const y2 = (await c.state()).player.yaw; await page.mouse.move(c.mx + 300, c.my); c.mx += 300; await sleep(150); const y3 = (await c.state()).player.yaw;
  c.step('scoped sensitivity scales down (zoom 1 ≈ 40/90)', Math.abs(y3 - y2) < Math.abs(y1 - y0) * 0.6, `unscoped ${Math.abs(y1 - y0).toFixed(3)} scoped ${Math.abs(y3 - y2).toFixed(3)}`);
  await c.aimAtPoint(38, 1.2, 0); await sleep(300);
  await c.events(); await c.click(60); await sleep(150); const sA = (await c.state()).player; await sleep(1800); const sB = (await c.state()).player; const hurt = (await c.events('hurt')).filter(e => e.p.actorId === enemy.id);
  c.step('AWP shot hits scoped target and unscopes immediately', hurt.length > 0 && sA.zoom === 0, `damage ${hurt[0]?.p.damage} zoom after shot ${sA.zoom}`);
  c.step('rechamber then automatic re-scope to previous level', sB.zoom === 1 && !sB.needsRechamber, sB); await c.shot('awp_rescoped');
  await c.events(); for (let i = 0; i < 6; i++) { await c.click(20, 'right'); await sleep(40); } await sleep(300);
  await c.press('Digit2'); await sleep(80); await c.press('Digit1'); await sleep(80); await c.click(40); await sleep(80); await c.press('Digit2'); await sleep(80); await c.press('Digit1'); await sleep(80); await c.click(40); await sleep(500);
  const shots = (await c.events('shot')).filter(e => e.p.weapon === 'awp'); c.step('rapid switch/fire respects AWP cycle (≤1 extra shot)', shots.length <= 1, `${shots.length} awp shots in 1 s`);
  await sleep(1500); await c.press('Digit1'); await sleep(1500);
  await c.click(60, 'right'); await sleep(300); await c.press('Digit2'); await sleep(400); const fS = await c.ev(() => window.__cs2.fov()); c.step('switch while scoped restores FOV and clears overlay', fS.target === f0.target && !fS.scopeOverlay && fS.viewmodelVisible, fS);
  await c.press('Digit1'); await sleep(1400); await c.click(60, 'right'); await sleep(300); await c.press('KeyG'); await sleep(400); const fD = await c.ev(() => window.__cs2.fov()); c.step('drop while scoped restores FOV', fD.target === f0.target && !fD.scopeOverlay); await c.press('KeyE'); await sleep(800);
  await c.click(60, 'right'); await sleep(300); const magP = (await c.state()).player.mag; await c.press('Escape'); await sleep(300); await page.click('#pause [data-q="resume"]'); await sleep(500); const fP = await c.ev(() => window.__cs2.fov()); const sP = (await c.state()).player;
  c.step('pause/resume while scoped keeps state coherent and fires nothing', sP.mag === magP && sP.zoom === 1 && fP.scopeOverlay, { zoom: sP.zoom, mag: sP.mag });
  await page.evaluate(() => { const s = window.__cs2.settings(); s.fov = 80; window.__cs2.app.applySettings(s); }); await sleep(100); await c.click(60, 'right'); await sleep(100); await c.click(60, 'right'); await sleep(400); const fB = await c.ev(() => window.__cs2.fov()); c.step('base FOV changed while scoped is restored correctly', fB.target === 80, fB);
  await c.click(60, 'right'); await sleep(300); await c.ev(() => window.__cs2.killActor(1)); await sleep(500); const fK = await c.ev(() => window.__cs2.fov()); c.step('death while scoped clears overlay', !fK.scopeOverlay); await c.shot('awp_dead');
  await c.ev(() => window.__cs2.startMatch('CT', 'easy', 62)); await c.waitFor(() => window.__cs2.state().app === 'match', null, 20000); await sleep(500); await c.ensureLocked(); await c.ev(() => window.__cs2.freezeBots(true)); await c.ev(() => window.__cs2.setPhaseTime(0.3)); await c.waitPhase('live'); await c.ev(() => window.__cs2.setPhaseTime(600));
  const en2 = (await c.ev(() => window.__cs2.actors())).find(a => a.team === 'T'); await c.ev(id => window.__cs2.teleport(38, 0, 180, id), en2.id); await c.ev(() => window.__cs2.teleport(38, 6, 0)); await sleep(300); c.mx = 640; c.my = 360; await c.press('Digit3'); await sleep(800); await c.aimAtPoint(38, 1.2, 0); await c.events(); await c.click(60); await sleep(600);
  const farHurt = (await c.events('hurt')).length; c.step('knife swing at 6 m misses', farHurt === 0);
  await c.ev(() => window.__cs2.teleport(38, 1.0, 0)); await sleep(300); await c.aimAtPoint(38, 1.2, 0); await c.click(60); await sleep(600); const slash = (await c.events('hurt'))[0]; c.step('knife slash at 1 m hits for ~40', !!slash && slash.p.damage >= 30, slash?.p);
  await sleep(500); await c.click(60, 'right'); await sleep(800); const stab = (await c.events('hurt'))[0]; c.step('knife stab (RMB) hits harder', !!stab && stab.p.damage > (slash?.p.damage ?? 0), stab?.p); await c.shot('knife');
  c.step('no console errors', c.log.errors.length === 0, c.log.errors.slice(0, 3));
}
