/** Procedural WebAudio sound design: all sounds synthesised at runtime (no external audio assets). */
export class AudioSys {
  ctx: AudioContext | null = null; master!: GainNode; volume = 0.6; listener: { x: number; y: number; z: number; yaw: number } = { x: 0, y: 0, z: 0, yaw: 0 };
  private noiseBuf: AudioBuffer | null = null; private lastBeep = 0;
  activeVoices = 0;
  ensure() { if (this.ctx) { if (this.ctx.state === 'suspended') this.ctx.resume(); return; } this.ctx = new AudioContext(); this.master = this.ctx.createGain(); this.master.gain.value = this.volume; this.master.connect(this.ctx.destination); const n = this.ctx.createBuffer(1, this.ctx.sampleRate * 2, this.ctx.sampleRate); const d = n.getChannelData(0); for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1; this.noiseBuf = n; }
  setVolume(v: number) { this.volume = v; if (this.master) this.master.gain.value = v; }
  suspend() { this.ctx?.suspend(); } resume() { this.ctx?.resume(); }
  /** Spatialise: returns gain + pan for a world position relative to the listener. */
  private spatial(x: number, y: number, z: number, refDist: number, maxDist: number): { gain: number; pan: number } | null {
    const dx = x - this.listener.x, dy = y - this.listener.y, dz = z - this.listener.z; const d = Math.hypot(dx, dy, dz);
    if (d > maxDist) return null;
    const gain = d < refDist ? 1 : Math.max(0, 1 - (d - refDist) / (maxDist - refDist)) ** 1.6;
    const right = Math.cos(this.listener.yaw), rz = -Math.sin(this.listener.yaw); const pan = d > 0.3 ? Math.max(-1, Math.min(1, (dx * right + dz * rz) / d)) : 0;
    return { gain, pan };
  }
  private play(build: (ctx: AudioContext, out: AudioNode, t: number) => void, gain: number, pan: number, dur: number) {
    if (!this.ctx || gain <= 0.001 || this.activeVoices > 40) return; const ctx = this.ctx; const g = ctx.createGain(); g.gain.value = gain; const p = ctx.createStereoPanner(); p.pan.value = pan; g.connect(p).connect(this.master);
    this.activeVoices++; setTimeout(() => this.activeVoices--, dur * 1000 + 50);
    build(ctx, g, ctx.currentTime);
  }
  private noise(ctx: AudioContext, out: AudioNode, t: number, dur: number, f0: number, f1: number, q: number, env: (g: GainNode) => void, type: BiquadFilterType = 'bandpass') {
    const src = ctx.createBufferSource(); src.buffer = this.noiseBuf!; const f = ctx.createBiquadFilter(); f.type = type; f.frequency.setValueAtTime(f0, t); f.frequency.exponentialRampToValueAtTime(Math.max(20, f1), t + dur); f.Q.value = q; const g = ctx.createGain(); env(g); src.connect(f).connect(g).connect(out); src.start(t); src.stop(t + dur + 0.05);
  }
  gunshot(weapon: string, x: number, y: number, z: number, isLocal: boolean) {
    const s = isLocal ? { gain: 1, pan: 0 } : this.spatial(x, y, z, 6, 120); if (!s) return;
    const big = weapon === 'awp', pistol = weapon === 'usp' || weapon === 'glock', supp = weapon === 'usp';
    const vol = (big ? 1.0 : pistol ? (supp ? 0.35 : 0.6) : 0.85) * s.gain * (isLocal ? 0.7 : 1);
    this.play((ctx, out, t) => {
      const dur = big ? 0.6 : pistol ? 0.18 : 0.28;
      this.noise(ctx, out, t, dur, big ? 1200 : supp ? 900 : 2500, 120, 0.7, g => { g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + dur); }, supp ? 'lowpass' : 'bandpass');
      // low thump body
      const o = ctx.createOscillator(); o.type = 'sine'; o.frequency.setValueAtTime(big ? 140 : 180, t); o.frequency.exponentialRampToValueAtTime(40, t + 0.15); const g = ctx.createGain(); g.gain.setValueAtTime(supp ? 0.25 : 0.8, t); g.gain.exponentialRampToValueAtTime(0.001, t + (big ? 0.3 : 0.14)); o.connect(g).connect(out); o.start(t); o.stop(t + 0.35);
      if (!isLocal && s.gain < 0.6) { this.noise(ctx, out, t + 0.03, 0.5, 600, 100, 0.5, g2 => { g2.gain.setValueAtTime(0.35, t + 0.03); g2.gain.exponentialRampToValueAtTime(0.001, t + 0.5); }, 'lowpass'); }
    }, vol, s.pan, 0.7);
  }
  dryFire() { this.play((ctx, out, t) => { const o = ctx.createOscillator(); o.type = 'square'; o.frequency.value = 900; const g = ctx.createGain(); g.gain.setValueAtTime(0.15, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.05); o.connect(g).connect(out); o.start(t); o.stop(t + 0.06); }, 0.5, 0, 0.1); }
  click(pitch = 1, vol = 0.3) { this.play((ctx, out, t) => { this.noise(ctx, out, t, 0.05, 3000 * pitch, 800 * pitch, 2, g => { g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.05); }); }, vol, 0, 0.1); }
  reload(stage: 'start' | 'insert' | 'end', x: number, y: number, z: number, isLocal: boolean) { const s = isLocal ? { gain: 0.6, pan: 0 } : this.spatial(x, y, z, 3, 18); if (!s) return; if (stage === 'start') { this.click(0.6, s.gain * 0.5); } else if (stage === 'insert') { this.play((ctx, out, t) => { this.noise(ctx, out, t, 0.12, 1200, 300, 1.5, g => { g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.12); }); const o = ctx.createOscillator(); o.frequency.value = 220; const g = ctx.createGain(); g.gain.setValueAtTime(0.3, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.1); o.connect(g).connect(out); o.start(t); o.stop(t + 0.12); }, s.gain, s.pan, 0.2); } else this.click(1.4, s.gain * 0.6); }
  impact(surface: string | null, x: number, y: number, z: number) { const s = this.spatial(x, y, z, 4, 40); if (!s) return; const metal = surface?.startsWith('metal'); const flesh = surface === 'flesh'; this.play((ctx, out, t) => { if (flesh) this.noise(ctx, out, t, 0.12, 500, 150, 1, g => { g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.12); }, 'lowpass'); else if (metal) { const o = ctx.createOscillator(); o.frequency.value = 1800 + Math.random() * 800; const g = ctx.createGain(); g.gain.setValueAtTime(0.5, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.25); o.connect(g).connect(out); o.start(t); o.stop(t + 0.3); this.noise(ctx, out, t, 0.08, 4000, 1500, 1, g2 => { g2.gain.setValueAtTime(0.6, t); g2.gain.exponentialRampToValueAtTime(0.001, t + 0.08); }); } else this.noise(ctx, out, t, 0.09, 2200, 400, 0.8, g => { g.gain.setValueAtTime(0.8, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.09); }); }, s.gain * 0.5, s.pan, 0.3); }
  footstep(surface: string, x: number, y: number, z: number, isLocal: boolean) { const s = isLocal ? { gain: 0.35, pan: 0 } : this.spatial(x, y, z, 2, 26); if (!s) return; const stone = surface === 'stone' || surface === 'asphalt' || surface === 'ceiling'; const wood = surface === 'timber' || surface === 'crate' || surface === 'woodOld'; this.play((ctx, out, t) => { this.noise(ctx, out, t, 0.09, stone ? 1800 : wood ? 500 : 900, stone ? 500 : 200, 0.9, g => { g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.09); }, wood ? 'lowpass' : 'bandpass'); }, s.gain * (wood ? 0.7 : 0.5), s.pan, 0.15); }
  explosion(x: number, y: number, z: number, big: boolean) { const s = this.spatial(x, y, z, big ? 20 : 8, 200); if (!s) return; this.play((ctx, out, t) => { const dur = big ? 2.2 : 0.9; this.noise(ctx, out, t, dur, 800, 40, 0.5, g => { g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + dur); }, 'lowpass'); const o = ctx.createOscillator(); o.frequency.setValueAtTime(90, t); o.frequency.exponentialRampToValueAtTime(25, t + 0.6); const g = ctx.createGain(); g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + (big ? 1.2 : 0.5)); o.connect(g).connect(out); o.start(t); o.stop(t + 1.5); }, s.gain * (big ? 1.2 : 0.9), s.pan, 2.5); }
  flashPop(x: number, y: number, z: number) { const s = this.spatial(x, y, z, 6, 60); if (!s) return; this.play((ctx, out, t) => { this.noise(ctx, out, t, 0.3, 4000, 1000, 0.8, g => { g.gain.setValueAtTime(1, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.3); }); const o = ctx.createOscillator(); o.frequency.value = 3200; const g = ctx.createGain(); g.gain.setValueAtTime(0.25 * s.gain, t); g.gain.exponentialRampToValueAtTime(0.001, t + 1.2); o.connect(g).connect(out); o.start(t); o.stop(t + 1.3); }, s.gain, s.pan, 1.4); }
  smokePop(x: number, y: number, z: number) { const s = this.spatial(x, y, z, 5, 40); if (!s) return; this.play((ctx, out, t) => { this.noise(ctx, out, t, 1.6, 900, 300, 0.6, g => { g.gain.setValueAtTime(0.5, t); g.gain.linearRampToValueAtTime(0.35, t + 0.5); g.gain.exponentialRampToValueAtTime(0.001, t + 1.6); }, 'lowpass'); }, s.gain * 0.7, s.pan, 1.7); }
  fireLoop(x: number, y: number, z: number) { const s = this.spatial(x, y, z, 3, 22); if (!s) return; this.play((ctx, out, t) => { this.noise(ctx, out, t, 0.5, 400, 300, 0.5, g => { g.gain.setValueAtTime(0.3, t); g.gain.linearRampToValueAtTime(0.3, t + 0.4); g.gain.linearRampToValueAtTime(0.001, t + 0.5); }, 'lowpass'); }, s.gain * 0.5, s.pan, 0.55); }
  bounce(x: number, y: number, z: number, speed: number) { const s = this.spatial(x, y, z, 3, 30); if (!s) return; this.play((ctx, out, t) => { const o = ctx.createOscillator(); o.frequency.value = 900 + Math.random() * 300; const g = ctx.createGain(); g.gain.setValueAtTime(0.4, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.08); o.connect(g).connect(out); o.start(t); o.stop(t + 0.1); }, s.gain * Math.min(1, speed / 8) * 0.6, s.pan, 0.15); }
  bombBeep(x: number, y: number, z: number, urgency: number) { const s = this.spatial(x, y, z, 12, 140); if (!s) return; this.play((ctx, out, t) => { const o = ctx.createOscillator(); o.type = 'square'; o.frequency.value = 1400 + urgency * 400; const g = ctx.createGain(); g.gain.setValueAtTime(0.18, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.09); o.connect(g).connect(out); o.start(t); o.stop(t + 0.1); }, Math.max(0.2, s.gain), s.pan, 0.12); }
  plantTick() { this.play((ctx, out, t) => { const o = ctx.createOscillator(); o.type = 'square'; o.frequency.value = 2200; const g = ctx.createGain(); g.gain.setValueAtTime(0.12, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.04); o.connect(g).connect(out); o.start(t); o.stop(t + 0.05); }, 0.6, 0, 0.06); }
  defuseHum() { this.play((ctx, out, t) => { this.noise(ctx, out, t, 0.2, 3000, 2500, 3, g => { g.gain.setValueAtTime(0.15, t); g.gain.linearRampToValueAtTime(0.001, t + 0.2); }); }, 0.6, 0, 0.25); }
  knife(hit: boolean) { this.play((ctx, out, t) => { this.noise(ctx, out, t, 0.15, hit ? 700 : 3000, hit ? 200 : 1200, 1, g => { g.gain.setValueAtTime(0.7, t); g.gain.exponentialRampToValueAtTime(0.001, t + 0.15); }, hit ? 'lowpass' : 'bandpass'); }, 0.5, 0, 0.2); }
  ui(kind: 'hover' | 'click' | 'buy' | 'deny' | 'roundwin' | 'roundlose' | 'kill' | 'headshot' | 'hurt' | 'zoom') {
    this.play((ctx, out, t) => {
      const o = ctx.createOscillator(); const g = ctx.createGain(); o.connect(g).connect(out);
      const tone = (f: number, d: number, type: OscillatorType = 'sine', v = 0.3) => { o.type = type; o.frequency.setValueAtTime(f, t); g.gain.setValueAtTime(v, t); g.gain.exponentialRampToValueAtTime(0.001, t + d); o.start(t); o.stop(t + d + 0.02); };
      switch (kind) { case 'hover': tone(1200, 0.04, 'sine', 0.08); break; case 'click': tone(800, 0.06, 'triangle', 0.2); break; case 'buy': o.frequency.setValueAtTime(600, t); o.frequency.exponentialRampToValueAtTime(1200, t + 0.12); tone(600, 0.15, 'triangle', 0.25); break; case 'deny': tone(200, 0.2, 'square', 0.15); break;
        case 'roundwin': o.frequency.setValueAtTime(520, t); o.frequency.setValueAtTime(660, t + 0.15); o.frequency.setValueAtTime(880, t + 0.3); tone(520, 0.9, 'triangle', 0.3); break; case 'roundlose': o.frequency.setValueAtTime(440, t); o.frequency.setValueAtTime(330, t + 0.2); o.frequency.setValueAtTime(220, t + 0.4); tone(440, 1.0, 'triangle', 0.3); break;
        case 'kill': tone(1500, 0.08, 'square', 0.12); break; case 'headshot': o.frequency.setValueAtTime(1800, t); o.frequency.setValueAtTime(2400, t + 0.05); tone(1800, 0.12, 'square', 0.15); break; case 'hurt': tone(160, 0.15, 'sawtooth', 0.25); break; case 'zoom': tone(2600, 0.05, 'sine', 0.12); break; }
    }, 1, 0, 1.1);
  }
  bombTicker(dt: number, planted: { x: number; y: number; z: number; timeLeft: number } | null, total: number) { if (!planted) return; const u = 1 - Math.max(0, planted.timeLeft) / total; const interval = Math.max(0.12, 1.0 - u * u * 0.95); this.lastBeep += dt; if (this.lastBeep >= interval) { this.lastBeep = 0; this.bombBeep(planted.x, planted.y, planted.z, u); } }
}
