import { launch, shot, st, sleep, startMatchUI, writeJson, holdKey } from './lib.mjs';
const out = process.argv[2] ?? 'evidence/dev';
const { browser, page, log } = await launch({ width: 1280, height: 720 });
const s0 = await startMatchUI(page, { team: 'T', difficulty: 'easy', seed: 42 });
console.log('locked', s0.locked, 'phase', s0.phase);
await page.keyboard.press('KeyB'); await sleep(500); console.log('buyOpen', (await st(page)).buyOpen); await shot(page, `${out}/buy.png`);
await page.click('#buy .item[data-item="ak47"]'); await page.click('#buy .item[data-item="helmet"]'); await sleep(200);
console.log('after buy', JSON.stringify((await st(page)).player).slice(0, 200));
await page.keyboard.press('KeyB'); await sleep(600); console.log('locked after buy close', (await st(page)).locked, 'buyOpen', (await st(page)).buyOpen);
const t0 = Date.now(); await page.waitForFunction(() => window.__cs2.state().phase === 'live', null, { timeout: 90000 }); console.log('freeze took', ((Date.now() - t0) / 1000).toFixed(1), 's real');
await holdKey(page, 'KeyW', 2500);
const p1 = (await st(page)).player; console.log('moved to', p1.x, p1.z);
await page.mouse.move(640, 360); await page.mouse.move(740, 360, { steps: 10 });
await page.mouse.down(); await sleep(400); await page.mouse.up(); await sleep(200);
const p2 = (await st(page)).player; console.log('after fire mag', p2.mag, 'yaw', p2.yaw);
await shot(page, `${out}/live.png`);
await page.keyboard.press('KeyR'); await sleep(300); console.log('reloading', (await st(page)).player.action);
console.log('perf', JSON.stringify(await page.evaluate(() => { const p = window.__cs2.perf(); return { cpuMed: p.cpuMedianMs, fps: p.fps, calls: p.drawCalls }; })));
console.log('nav', JSON.stringify(await page.evaluate(() => window.__cs2.navCheck())));
await page.keyboard.down('Tab'); await sleep(300); await shot(page, `${out}/scoreboard.png`); await page.keyboard.up('Tab');
await page.keyboard.press('Escape'); await sleep(300); await shot(page, `${out}/pause.png`); console.log('paused', (await st(page)).paused);
await page.click('#pause [data-q="resume"]'); await sleep(400); console.log('resumed locked', (await st(page)).locked);
writeJson(`${out}/smoke-log.json`, log);
console.log('errors', log.errors.slice(0, 10));
await browser.close();
